#ifndef _INC_WDSCLIENTAPI
#define _INC_WDSCLIENTAPI
#include <windows.h>
#if (_WIN32_WINNT >= 0x0600)

#ifndef WDSTCIAPI
#define WDSTCIAPI WINAPI
#endif

/* CALLBACKS

VOID CALLBACK PFN_WdsTransportClientReceiveContents(
  HANDLE hSessionKey,
  PVOID pCallerData,
  PVOID pMetadata,
  ULONG ulSize,
  PULARGE_INTEGER pContentOffset
);

VOID CALLBACK PFN_WdsTransportClientReceiveMetadata(
  __in  HANDLE hSessionKey,
  __in  PVOID pCallerData,
  __in  PVOID pMetadata,
  __in  ULONG ulSize
);

VOID CALLBACK PFN_WdsTransportClientSessionComplete(
  __in  HANDLE hSessionKey,
  __in  PVOID pCallerData,
  __in  DWORD dwError
);

VOID CALLBACK PFN_WdsTransportClientSessionStart(
  __in  HANDLE hSessionKey,
  __in  PVOID pCallerData,
  __in  PULARGE_INTEGER FileSize
);

VOID CALLBACK PFN_WdsTransportClientSessionStartEx(
  __in  HANDLE hSessionKey,
  __in  PVOID pCallerData,
  __in  PTRANSPORTCLIENT_SESSION_INFO Info
);

*/

typedef enum _TRANSPORTCLIENT_CALLBACK_ID {
  WDS_TRANSPORTCLIENT_SESSION_START      = 0,
  WDS_TRANSPORTCLIENT_RECEIVE_CONTENTS   = 1,
  WDS_TRANSPORTCLIENT_SESSION_COMPLETE   = 2,
  WDS_TRANSPORTCLIENT_RECEIVE_METADATA   = 3,
  WDS_TRANSPORTCLIENT_SESSION_STARTEX    = 4,
  WDS_TRANSPORTCLIENT_MAX_CALLBACKS      = 5 
} TRANSPORTCLIENT_CALLBACK_ID,*PTRANSPORTCLIENT_CALLBACK_ID;

typedef enum _TRANSPORTPROVIDER_CALLBACK_ID {
  WDS_TRANSPORTPROVIDER_CREATE_INSTANCE         = 0,
  WDS_TRANSPORTPROVIDER_COMPARE_CONTENT         = 1,
  WDS_TRANSPORTPROVIDER_OPEN_CONTENT            = 2,
  WDS_TRANSPORTPROVIDER_USER_ACCESS_CHECK       = 3,
  WDS_TRANSPORTPROVIDER_GET_CONTENT_SIZE        = 4,
  WDS_TRANSPORTPROVIDER_READ_CONTENT            = 5,
  WDS_TRANSPORTPROVIDER_CLOSE_CONTENT           = 6,
  WDS_TRANSPORTPROVIDER_CLOSE_INSTANCE          = 7,
  WDS_TRANSPORTPROVIDER_SHUTDOWN                = 8,
  WDS_TRANSPORTPROVIDER_DUMP_STATE              = 9,
  WDS_TRANSPORTPROVIDER_REFRESH_SETTINGS        = 10,
  WDS_TRANSPORTPROVIDER_GET_CONTENT_METADATA    = 11,
  WDS_TRANSPORTPROVIDER_MAX_CALLBACKS           = 12 
} TRANSPORTPROVIDER_CALLBACK_ID, *PTRANSPORTPROVIDER_CALLBACK_ID;

typedef struct _TRANSPORTCLIENT_SESSION_INFO {
  ULONG          ulStructureLength;
  ULARGE_INTEGER ullFileSize;
  ULONG          ulBlockSize;
} TRANSPORTCLIENT_SESSION_INFO, *PTRANSPORTCLIENT_SESSION_INFO;

DWORD WDSTCIAPI WdsTransportClientStartSession(
  HANDLE hSessionKey
);

#endif /*(_WIN32_WINNT >= 0x0600)*/
#endif /*_INC_WDSCLIENTAPI*/
